#!/usr/bin/env bash

cd /home/dalamud/xivapi.com && bash /home/dalamud/xivapi.com/update &&
cd /home/dalamud/xivapi.com.beta && bash /home/dalamud/xivapi.com.beta/update &&
cd /home/dalamud/mogboard.com && bash /home/dalamud/mogboard.com/update &&
cd /home/dalamud/mogboard.com.beta && bash /home/dalamud/mogboard.com.beta/update
